version: "3"
services:
  db:
    image: "postgres:11"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis:/data
  api:
    build:
      context: ./api
    depends_on:
      - db
      - redis
  web:
    build:
      context: ./web
