version: "3"
services:
  web:
    build:
      context: ./web
    environment:
      PORT: 5000
      DOMAIN: stickerity.local
    volumes:
      - ./web:/srv/web
    ports:
      - 5000:5000
    command: ["npm", "start"]

  nginx:
    image: "nginx"
    volumes:
      - ./nginx:/srv/nginx
      - ./ssl:/srv/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5080:80"
    depends_on:
      - web

