version: "3"
services:
  web:
    build:
      context: ./web
      args:
        - DOMAIN=stickerity.com
    environment:
      PORT: 5000
      DOMAIN: stickerity.com

  nginx:
    image: "nginx"
    volumes:
      - ./nginx:/srv/nginx
      - ./ssl:/srv/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5080:80"
    depends_on:
      - web
