version: "3"
services:
  db:
    image: "postgres:11"
    environment:
      POSTGRES_USER: stickerity
      POSTGRES_PASSWORD: stickerity
      POSTGRES_DB: stickerity
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/data/postgresql:/var/lib/postgresql/data
  api:
    build:
      context: ./api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: stickerity
      DB_USER: stickerity
      DB_PASSWORD: stickerity
      SECRET: my_very_strong_secret
    depends_on:
      - db
  web:
    build:
      context: ./web
      args:
        - DOMAIN=stickerity.com
    environment:
      PORT: 5000
      DOMAIN: stickerity.com

  nginx:
    image: "nginx"
    volumes:
      - ./nginx:/srv/nginx
      - ./ssl:/srv/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - web
